name: Deploy Infrastructure with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Verify Terraform Directory
        run: |
          if [ ! -d "./terraform" ]; then
            echo "Terraform directory does not exist"
            exit 1
          fi

      - name: Initialize Terraform
        id: init_terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validate Terraform
        id: validate_terraform
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Apply
        id: apply_terraform
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve -parallelism=10
