name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t hello-world-nodejs:latest .

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.115134429501 }}.dkr.ecr.${{ secrets.us-west-2 }}.amazonaws.com
        env:
          AWS_REGION: ${{ secrets.us-west-2 }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIARVTUL7E63HCYOR5Y }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.jtzuxdjHM6BW/UQfg4IQRZocgcR0Ot30GBIREr38
 }}

      - name: Push Docker image to Amazon ECR
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_115134429501}}
          AWS_REGION: ${{ secrets.us-west-2 }}
          IMAGE_REPO_NAME: hello-world-nodejs
        run: |
          docker tag hello-world-nodejs:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  deploy:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform
