- name: Print environment variables
  run: |
    echo $AWS_ACCESS_KEY_ID
    echo $AWS_SECRET_ACCESS_KEY
    echo $AWS_REGION
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AKIARVTUL7E63HCYOR5Y }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.jtzuxdjHM6BW/UQfg4IQRZocgcR0Ot30GBIREr38 }}
    AWS_REGION: ${{ secrets.us-west-2 }}
