    - name: Debug Environment Variables
      run: |
        echo "AWS_ACCESS_KEY_ID is set"
        echo "AWS_SECRET_ACCESS_KEY is set"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
