name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  login-to-amazon-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-region: us-west-2
          mask-aws-account-id: 'false'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

    # Define outputs to use in subsequent steps
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
      docker_username: ${{ steps.login-ecr.outputs.docker_username_115134429501_dkr_ecr_us_west_2_amazonaws_com }} # Adjust the output name based on actual output
      docker_password: ${{ steps.login-ecr.outputs.docker_password_115134429501_dkr_ecr_us_west_2_amazonaws_com }} # Adjust the output name based on actual output

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: login-to-amazon-ecr

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Use the outputs from the previous job
      - name: Use ECR credentials from login job
        run: echo "Registry: ${{ needs.login-to-amazon-ecr.outputs.registry }}"

      # Additional steps for building and deploying can follow here
