- name: Checkout code
  uses: actions/checkout@v2

- name: Set up Node.js
  uses: actions/setup-node@v2
  with:
    node-version: '22'

 - name: Install dependencies
  run: npm install

- name: Build Docker image
  run: docker build -t hello-world-nodejs:latest .

- name: Log in to Amazon ECR
  uses: aws-actions/amazon-ecr-login@v1
  with:
    registry-type: ecr
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ${{ secrets.AWS_REGION }}

