name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0  # Specify the exact version you need

    - name: Debug AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

    - name: Terraform Init
      run: terraform init -input=false -backend=true
      working-directory: ./terraform

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve -input=false \
          -var "aws_access_key_id=${AWS_ACCESS_KEY_ID}" \
          -var "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}"
      working-directory: ./terraform
